# Generated by Django 4.2.7 on 2023-11-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Potency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potency', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('updated', models.DateTimeField(verbose_name='date last updated')),
            ],
        ),
        migrations.CreateModel(
            name='RemedyPotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='homeo.potency')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeo.remedy')),
            ],
        ),
        migrations.CreateModel(
            name='RemedyMateriaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiaMedica', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='homeo.materiamedica')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeo.remedy')),
            ],
        ),
    ]
