# Generated by Django 4.2.7 on 2023-11-26 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotencyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availablePotency', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastUpdated', models.DateTimeField(default=datetime.datetime(2023, 11, 26, 0, 48, 26, 499888))),
            ],
        ),
        migrations.CreateModel(
            name='Potency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeo.potencylist')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeo.remedy')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('data', models.TextField()),
                ('description', models.CharField(default='', max_length=100)),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeo.remedy')),
            ],
        ),
    ]
