# Generated by Django 4.2.7 on 2023-11-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedy',
            name='created',
        ),
        migrations.RemoveField(
            model_name='remedy',
            name='updated',
        ),
    ]
