# Generated by Django 4.2.7 on 2023-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeo', '0002_rename_potency_remedypotency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiamedica',
            name='remedy',
        ),
        migrations.RemoveField(
            model_name='remedy',
            name='lastUpdated',
        ),
        migrations.AddField(
            model_name='remedy',
            name='materiaMedica',
            field=models.ManyToManyField(null=True, to='homeo.materiamedica'),
        ),
        migrations.AddField(
            model_name='remedy',
            name='potency',
            field=models.ManyToManyField(null=True, to='homeo.potencylist'),
        ),
        migrations.DeleteModel(
            name='RemedyPotency',
        ),
    ]
